version: "3.0"
services:
  db:
    container_name: "delivery_db"
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5430:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge